###cadastrar
POST http://localhost:5253/api/professor/cadastrar
Content-Type: application/json

{
    "nome": "João Silva",
    "endereco": "Rua das Flores, 123",
    "telefone": "1234-5678",
    "email": "joao.silva@example.com",
    "senha": "senhaSegura123!"
}

###listar
GET http://localhost:5253/api/professor/listar

###buscar
POST http://localhost:5253/api/professor/buscar
Content-Type: application/json

"adfa87a5-7f01-4f1e-b3dc-096ae3f97cff"

###remover
DELETE http://localhost:5253/api/professor/remover
Content-Type: application/json

"2d6b597a-4762-4bfb-942c-aee97088fcb7"


###alterar
PUT http://localhost:5253/api/professor/alterar
Content-Type: application/json

{
    "id": "adfa87a5-7f01-4f1e-b3dc-096ae3f97cff",
    "nome": "João Silva Alterado",
    "endereco": "Rua das Flores, 456",
    "telefone": "9876-5432",
    "email": "joao.silva.alterado@example.com",
    "senha": "novaSenhaSegura123!"
}

