### CADASTRAR PROFESSOR
PUT  http://localhost:5199/api/professor/cadastrar
Content-Type: application/json

{
    "nome": "Lucas Almeida",
    "endereco": "Avenida Brasil, 45",
    "telefone": "41 995432109",
    "login": "lucas.almeida@hotmail.com",
    "senha": "lucas1234"
}

### LISTAR PROFESSORES
GET  http://localhost:5199/api/professor/listar

### BUSCAR PROFESSOR
POST  http://localhost:5199/api/professor/buscar
Content-Type: application/json

"7593f813-32f2-4726-ab2f-4f8c304d60c0"


### REMOVER PROFESSOR
DELETE  http://localhost:5199/api/professor/remover
Content-Type: application/json

"5b40c6c9-a7ce-47ad-b2f6-9d33080d7085"


### ALTERAR PROFESSOR POR ID
PUT  http://localhost:5199/api/professor/alterar
Content-Type: application/json

{
   "Id" : "7593f813-32f2-4726-ab2f-4f8c304d60c0",
   "nome": "aaa",
   "endereco": "bbb, 12",
   "telefone": "41 sdas",
   "login": "asdasda.santos@gmail.com",
   "senha": "asdasd123"
}

### ALTERAR PROFESSOR POR ID PARCIAL
PUT  http://localhost:5199/api/professor/alterar
Content-Type: application/json

{
   "id" : "7593f813-32f2-4726-ab2f-4f8c304d60c0",
   "nome": "nome"
}