##CADASTRAR PLANO 
PUT http://localhost:5199/api/plano/cadastrar
Content-Type: application/json

{
    "nomePlano": "Plano Premium",
    "valor": 150.00
}

###LISTAR PLANO 
GET http://localhost:5199/api/plano/listar

###BUSCAR PLANO POR ID
POST http://localhost:5199/api/plano/buscar
Content-Type: application/json

"1"  // Substitua pelo ID do plano

###REMOVER PLANO
DELETE http://localhost:5199/api/plano/remover
Content-Type: application/json

"1"  // Substitua pelo ID do plano

###ALTERAR DADOS DO PLANO TOTAL
PUT http://localhost:5199/api/plano/alterar
Content-Type: application/json

{
   "Id": 1,  // Substitua pelo ID do plano
   "nomePlano": "Plano Gold",
   "valor": 200.00
}

###ALTERAR DADOS DO PLANO PARCIAL
PUT http://localhost:5199/api/plano/alterar
Content-Type: application/json

{
   "id": 1,  // Substitua pelo ID do plano
   "nomePlano": "Novo Nome"
}
