##CADASTRAR TRIENO
PUT http://localhost:5199/api/treino/cadastrar
Content-Type: application/json

{
    "descricao": "Treino Abdominal",
    "duracaoEmDias": 30
}

###LISTAR TRIENOS
GET http://localhost:5199/api/treino/listar

###BUSCAR TRIENO POR ID
POST http://localhost:5199/api/treino/buscar
Content-Type: application/json

"2"

###REMOVER TREINO 
DELETE http://localhost:5199/api/treino/remover
Content-Type: application/json

"b0457c0d-1ab9-434a-82ce-ea381eeac4dd"

###ALTERAR DADOS DO TRINEO TOTAL
PUT http://localhost:5199/api/treino/alterar
Content-Type: application/json

{
    "id": 2,
    "descricao": "Treino Avançado",
    "duracaoEmDias": 30
}

###ALTERAR DADOS DO TREINO PARCIAL
PUT http://localhost:5199/api/treino/alterar
Content-Type: application/json

{
    "id": 2,
    "duracaoEmDias": 10
}
