### Cadastrar treinos
POST http://localhost:5253/api/treinos/cadastrar
Content-Type: application/json

{
    "nome": "Treino Bala",
    "finalidade": "Aumento de massa muscular",
    "descricao": "Treino focado em hipertrofia",
    "nivelTreino": "Intermediário",
    "exercicios": [
        {
            "id": "90a45219-e239-4ecf-9d98-b09e5e47e1c8"
        },
        {
            "id": "c61551c3-41c1-4b23-9a56-eacfe542df03"
        }
    ]
}

### Listar treinos
GET http://localhost:5253/api/treinos/listar

### Buscar treinos por nome
GET http://localhost:5253/api/treinos/buscarPorNome/Treino AB

### Buscar treinos por ID
GET http://localhost:5253/api/treinos/buscarPorId/02519010-abef-40ba-91e1-379f6454d29b

### Deletar treinos
DELETE http://localhost:5253/api/treinos/deletar/13b0c1c7-9137-445a-baab-830eb32e7b60

### Alterar treinos
PUT http://localhost:5253/api/treinos/alterar/02519010-abef-40ba-91e1-379f6454d29b
Content-Type: application/json

{
    "nome": "Treino AB",
    "finalidade": "Definição muscular",
    "descricao": "Treino focado em definição",
    "nivelTreino": "Avançado",
    "exercicios": [
        {
            "id": "91ed587a-22a7-4b27-a4bb-3c98cf5ff7ca"
        },
                {
            "id": "41329ef6-72f7-4512-8251-828633e430e2"
        },
                {
            "id": "683a41d9-381b-41b1-b387-24d762bb5d8a"
        }
    ]
}