### Buscar por nome
GET http://localhost:5253/api/plano/buscar/Plano1

### Listar todos Planos
GET http://localhost:5253/api/plano/listar

### Deletar por Id
DELETE http://localhost:5253/api/plano/deletar/641c2a63-ac64-4b5b-94b5-ab48f344e546

### Mover aluno para novo plano
PUT http://localhost:5253/api/plano/mover-aluno/f25bf218-c98c-47ac-805d-117259216239/para-plano/beb97501-71e8-4bb0-a857-ae380183835c
Content-Type:  application/json

### Mover todos alunos de plano A para B
PUT http://localhost:5253/api/plano/mover-alunos/10/2
Content-Type: application/json


### Cadastrar plano 
POST http://localhost:5253/api/plano/cadastrar
Content-Type: application/json

{
    "nomePlano": "Plano1",
    "valor": 250,
    "parcelas": 4
}

### Atualizar plano
PUT http://localhost:5253/api/plano/atualizar/641c2a63-ac64-4b5b-94b5-ab48f344e546
Content-Type: application/json

{
    "nomePlano" : "Plano Especial",
    "valor" : 3500,
    "parcelas" : 1
 

    
}