### Cadastrar Aluno
POST  http://localhost:5253/api/aluno/cadastrar
Content-Type: application/json

   {
        "nome": "Patrícia Lima",
        "endereco": "Avenida Central, 101",
        "telefone": "41 994567123",
        "email": "patricia.lima@gmail.com",
        "senha": "patricia456!",
        "planoId": "334db27f-d803-4c58-b179-1058069bdfa4"
    }
    
### Atualizar Aluno por Id
PUT  http://localhost:5253/api/aluno/alterar/
Content-Type: application/json

{
   "id": "5bbca2bf-cdd9-48aa-8508-c52d2f5bdbb2",
   "nome": "Anderson",
   "endereco": "Rua Ososirio, 2",
   "telefone": "44 41528745",
   "email": "Alterado.santos@gmail",
   "senha": "Alterado123!"
}

### Buscar Aluno por ID
GET http://localhost:5253/api/aluno/buscar/1055c99a-6bdd-4c13-b6a4-da4ebcc48b39

### Listar todos alunos
GET http://localhost:5253/api/aluno/listar

### Deletar por Id
DELETE http://localhost:5253/api/aluno/deletar/f25bf218-c98c-47ac-805d-117259216239

###
PUT  http://localhost:5253/api/aluno/add-exercicio/5077cdbc-355c-4758-a0ac-4aad7941bfbf
Content-Type: application/json

"3e2280bf-69b9-4872-bb0c-634a3a8a1935"