### Buscar por nome
GET http://localhost:5253/api/plano/buscar/7340d798-d1de-4d33-8dbf-d52f996501ac

### Listar todos Planos
GET http://localhost:5253/api/plano/listar

### Deletar por Id
DELETE http://localhost:5253/api/plano/deletar/b42cafd1-8cf4-4962-801a-e03e21262314

### Mover aluno para novo plano (Alunoid/PlanoId)
PUT http://localhost:5253/api/plano/mover-aluno/81ac4ee8-d37b-4c11-95a6-1f2f2ebe4445/para-plano/fc4e2878-ee93-4e02-9c7f-4034b04754b2
Content-Type:  application/json

### Mover todos alunos de plano A para B (planoAntigoId/PlanoNovoId
PUT http://localhost:5253/api/plano/mover-alunos/fc4e2878-ee93-4e02-9c7f-4034b04754b2/6a30980a-07dd-4995-ae24-addc2d9e69db
Content-Type: application/json


### Cadastrar plano 
POST http://localhost:5253/api/plano/cadastrar
Content-Type: application/json

{
    "nomePlano": "Plano 2",
    "valor": 250,
    "parcelas": 4
}

### Atualizar plano
PUT http://localhost:5253/api/plano/atualizar/4ba18d0c-25c9-4f64-8cac-89cf9a951742
Content-Type: application/json

{
    "nomePlano" : "Plano",
    "valor" : 3500,
    "parcelas": 1
}