###cadastrar
POST http://localhost:5253/api/professor/cadastrar
Content-Type: application/json

{
    "nome": "Pedrinho",
    "endereco": "Rua das Flores, 123",
    "telefone": "1234-5678",
    "email": "joao.silva@example.com",
    "senha": "senhaSegura123!",
    "exercicioId" : "d0d2514b-d593-4715-a45b-33d748326e1f"
}

###listar
GET http://localhost:5253/api/professor/listar

###buscar
GET http://localhost:5253/api/professor/buscar/d0eebbeb-8f79-4cbf-ab45-4f7ea13dd181

###remover
DELETE http://localhost:5253/api/professor/remover/d0eebbeb-8f79-4cbf-ab45-4f7ea13dd181
Content-Type: application/json

###alterar
PUT http://localhost:5253/api/professor/alterar
Content-Type: application/json

{
    "id": "eaff546c-b397-47f6-a804-20f4fb9f290d",
    "nome": "Pedrinho Alterado",
    "endereco": "Rua das Flores, 456",
    "telefone": "9876-5432",
    "email": "joao.silva.alterado@example.com",
    "senha": "novaSenhaSegura123!"
}

