### Cadastrar exercicio
POST http://localhost:5253/api/exercicios/cadastrar
Content-Type: application/json

{
    "nome": "Teste bala",
    "grupoMuscular": "Teste",
    "descricao": "Exercício para fortalecer o peitoral.",
    "repeticoes": 15,
    "tempoDescanso": 60
}

### Listar exercicios
GET http://localhost:5253/api/exercicios/listar

### Buscar exercicios por nome
GET http://localhost:5253/api/exercicios/buscarPorNome/Teste Avançado

### Buscar exercicios por ID
GET http://localhost:5253/api/exercicios/buscar/9ddea3d8-ce64-489d-94ae-3c0868a9627d

### Deletar exercicios
DELETE http://localhost:5253/api/exercicios/deletar/9ddea3d8-ce64-489d-94ae-3c0868a9627d

### Alterar exercicios por ID
PUT http://localhost:5253/api/exercicios/alterar
Content-Type: application/json

{
  "id" : "039e4b38-f83e-46fa-a73b-34cad897650a",
  "nome": "Teste Avançado",
  "grupoMuscular": "Pernas",
  "descricao": "Exercício que foca nos músculos isquiotibiais e glúteos.",
  "repeticoes": 12,
  "tempoDescanso": 60
}

### Cadastrar lista de exercicios
POST http://localhost:5253/api/exercicios/cadastrarlista
Content-Type: application/json

[
  {
    "Nome": "Flexão",
    "grupoMuscular": "Peito",
    "Descricao": "Exercício que trabalha o peitoral, ombros e tríceps.",
    "Repeticoes": 15,
    "TempoDescanso": 45
  },
  {
    "Nome": "Puxada na Barra Fixa",
    "grupoMuscular": "Costas",
    "Descricao": "Fortalece os músculos das costas e bíceps.",
    "Repeticoes": 10,
    "TempoDescanso": 60
  },
  {
    "Nome": "Leg Press",
    "grupoMuscular": "Pernas",
    "Descricao": "Exercício de força que foca nos músculos das pernas.",
    "Repeticoes": 12,
    "TempoDescanso": 60
  },
  {
    "Nome": "Remada Curvada",
    "grupoMuscular": "Costas",
    "Descricao": "Foca nos músculos das costas e bíceps.",
    "Repeticoes": 12,
    "TempoDescanso": 60
  },
  {
    "Nome": "Abdômen Inverso",
    "grupoMuscular": "Abdômen",
    "Descricao": "Trabalha a parte inferior do abdômen.",
    "Repeticoes": 15,
    "TempoDescanso": 30
  },
  {
    "nome": "Flexão de Braços",
    "grupoMuscular": "Peito",
    "descricao": "Exercício para fortalecer o peitoral.",
    "repeticoes": 10,
    "TempoDescanso": 30
  },
  {
    "nome": "Flexão de Braços Inversa",
    "grupoMuscular": "Tríceps",
    "descricao": "Exercício para fortalecer os tríceps.",
    "repeticoes": 12,
    "TempoDescanso": 30
  }  
]